### ISSUE TITLE
configuration BridgePF

### ISSUE THREAD

**Issue by vcalfa** [Sage-Bionetworks/BridgePF#966]
Hi, I trying to configure BridgePF.

I use AWS and Stormpath free tier. 
On AWS I have configured four  users with access to S3 and DynamoDB.
Stormpath is been configured  too (I hope correct).

Can you give me some advice/ point  what I may having configured wrong, when I getting this error: 
Test fails too.

Thanks

```
--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

2016-01-06 10:17:27,404 INFO  [ForkJoinPool-1-worker-1] org.sagebionetworks.bridge.play.modules.BridgeSpringContextModule - Environment: LOCAL

2016-01-06 10:17:47,574 INFO  [ForkJoinPool-1-worker-1] org.sagebionetworks.bridge.dynamodb.DynamoInitializer - DynamoDB tables are ready.

2016-01-06 10:17:47,575 INFO  [ForkJoinPool-1-worker-1] org.sagebionetworks.bridge.play.modules.BridgeSpringContextModule - DynamoDB tables loaded.

2016-01-06 10:17:52,929 INFO  [ForkJoinPool-1-worker-1] org.sagebionetworks.bridge.config.BridgeSpringConfig - Using Redis Provider: redis.url

2016-01-06 10:18:01,974 INFO  [ForkJoinPool-1-worker-1] org.sagebionetworks.bridge.dynamodb.DynamoInitializer - DynamoDB tables are ready.

2016-01-06 10:18:03,569 WARN  [ForkJoinPool-1-worker-1] org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultStudyBootstrapper': Invocation of init method failed; nested exception is com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: O5R1UPKEVD60VIH65M90EOQ2JBVV4KQNSO5AEMVJF66Q9ASUAAJG)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context.jar:4.1.6.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context.jar:4.1.6.RELEASE]
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139) [spring-context.jar:4.1.6.RELEASE]
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83) [spring-context.jar:4.1.6.RELEASE]
    at org.sagebionetworks.bridge.play.modules.BridgeSpringContextModule.loadAppContext(BridgeSpringContextModule.java:37) [classes/:na]
    at org.sagebionetworks.bridge.play.modules.BridgeSpringContextModule.configure(BridgeSpringContextModule.java:27) [classes/:na]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) [guice.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) [guice.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) [guice.jar:na]
    at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177) [guice.jar:na]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) [guice.jar:na]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) [guice.jar:na]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) [guice.jar:na]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) [guice.jar:na]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) [guice.jar:na]
    at com.google.inject.Guice.createInjector(Guice.java:96) [guice.jar:na]
    at com.google.inject.Guice.createInjector(Guice.java:73) [guice.jar:na]
    at com.google.inject.Guice.createInjector(Guice.java:62) [guice.jar:na]
    at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126) [play_2.11-2.4.2.jar:2.4.2]
    at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93) [play_2.11-2.4.2.jar:2.4.2]
    at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21) [play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) [play-server_2.11-2.4.2.jar:2.4.2]
    at scala.Option.map(Option.scala:146) [scala-library-2.11.6.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) [play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Success.flatMap(Try.scala:230) [scala-library-2.11.6.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) [play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) [play-server_2.11-2.4.2.jar:2.4.2]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.6.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.6.jar:na]
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_45-internal]
Caused by: com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: O5R1UPKEVD60VIH65M90EOQ2JBVV4KQNSO5AEMVJF66Q9ASUAAJG)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182) ~[aws-java-sdk-core-1.10.20.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.10.20.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489) ~[aws-java-sdk-core-1.10.20.jar:na]
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310) ~[aws-java-sdk-core-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1776) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:1590) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:1241) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:937) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:1120) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:966) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:758) ~[aws-java-sdk-dynamodb-1.10.20.jar:na]
    at org.sagebionetworks.bridge.dynamodb.DynamoSubpopulationDao.createDefaultSubpopulation(DynamoSubpopulationDao.java:117) ~[classes/:na]
    at org.sagebionetworks.bridge.services.SubpopulationService.createDefaultSubpopulation(SubpopulationService.java:86) ~[classes/:na]
    at org.sagebionetworks.bridge.services.StudyServiceImpl.createStudy(StudyServiceImpl.java:135) ~[classes/:na]
    at org.sagebionetworks.bridge.DefaultStudyBootstrapper.initializeDatabase(DefaultStudyBootstrapper.java:42) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45-internal]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans.jar:4.1.6.RELEASE]
    ... 48 common frames omitted

2016-01-06 10:18:03,837 ERROR [New I/O worker #1] application - 

! @6okeao8ea - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Error creating bean with name 'defaultStudyBootstrapper': Invocation of init method failed; nested exception is com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: O5R1UPKEVD60VIH65M90EOQ2JBVV4KQNSO5AEMVJF66Q9ASUAAJG)
  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)

1 error]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.6.jar:na]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.2.jar:2.4.2]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.6.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.6.jar:na]
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[na:1.8.0_45-internal]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_45-internal]
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
```

**Comment by anmolg** [comment]
did anybody get to the bottom of the issue?

**Comment by DwayneJengSage** [comment]
It looks like we had inadvertently hardcoded our Stormpath directory into the DefaultStudyBootstrapper https://github.com/Sage-Bionetworks/BridgePF/blob/develop/app/org/sagebionetworks/bridge/DefaultStudyBootstrapper.java#L53

This will fail because you don't have permissions to our Stormpath bootstrapper. For the time being, you should edit this to point to your own Stormpath directory.

If you attempted to run the Bridge Server once and it failed on the DefaultStudyBootstrapper, this may have left your DynamoDB tables in bad state. You should empty out all DynamoDB tables before attempting to run Bridge Server again.

**Comment by syedaffanhamdani** [comment]
Hi,
I am trying to configure this project but getting this error:

Constructor threw exception; nested exception is com.amazonaws.SdkClientException: Unable to execute HTTP request: java.security.cert.CertificateException: No X509TrustManager implementation available

I used keytool to generate the jks file:

keytool -genkey -alias mydomain -keyalg RSA -keystore KeyStore.jks -keysize 2048

and then converted it to pem file to be uploaded to the aws key signing certificate. Did i do something wrong?
Thanks,
Affan

**Comment by DwayneJengSage** [comment]
Can you describe the command you used to start the server and post a full stack trace? Thanks!
